### ISSUE TITLE
Running this on a local machine. 

### ISSUE THREAD

**Issue by Shoshin23** [mortenjust/tensorswift-ios#1]
Hey @mortenjust. It's interesting to see someone attempt to get tensorflow and swift together. I stumbled on your work while searching for tensorflow and swift related projects. I just cloned this on my system and wanted to know how run it locally. Any help would be appreciated. :)

Thanks!

**Comment by Shoshin23** [comment]
I get a resource not found error for most of the tensorflow .h files though I did place the tensorswift-ios project folder within tensorflow-master folder.

**Comment by mortenjust** [comment]
Hey - thanks for trying! You may have to change some of the paths in Build Settings. The project assumes a Tensorflow installation at /Users/mortenjust/code/tensorflow. 

One thing you could do is to change those references to your own tensorflow installation and let me know if it works. 

As for this repo, I think it would make sense to link in the Tensorflow repo so you wouldn't have to change any references. Let me know if you (or anyone else reading this) know how to do this

![image](https://cloud.githubusercontent.com/assets/1548468/22477818/6b7b3c02-e79c-11e6-98b2-ae72931aa21d.png)

**Comment by mortenjust** [comment]
I just checked in a new version if you want to try. You still have to compile Tensorflow, I'm looking into ways to avoid this for the next push

**Comment by mortenjust** [comment]
Updated the README, take a look. If you're having trouble, please try github.com/mortenjust/trainer-mac for a fully automated experience
