### ISSUE TITLE
Nil pointer crash

### ISSUE THREAD

**Issue by BFMarks** [mortenjust/tensorswift-ios#2]
Running Swift 3 & Xcode 8.2.1 - The issue says "tensorflow/core/framework/types.h".  Any ideas?  Do I need to point the file at my Tensorflow main project?

**Comment by mortenjust** [comment]
Did you run setup.sh from terminal? If you're interested in a rough beta, I'm working on a mac app that sets everything up for you in one click, let me know

**Comment by BFMarks** [comment]
I did run setup.sh on my Mac Sierra 10.12 by using command `sh setup.sh`.  I believe that's the correct command.  I am very interested in the rough beta!  Please let me know the details.

**Comment by BFMarks** [comment]
Unless I'm totally off and need to do the `chmod +x setup.sh` and run `./setup.sh`?  Trying it now, I'll update the thread.

**Comment by mortenjust** [comment]
yes, `./setup.sh` should do it. How did it go? Here's [the automated macOS app](https://github.com/mortenjust/trainer-mac/releases). It's really hard to test, so any reports would be awesome

**Comment by BFMarks** [comment]
Hey Morten, 

Now it says `"unsupported/Eigen/CXX11/Tensor" file not found`, so making some progress but different errors.  Thanks for the Pre-Release!  Any other tips to make sure it runs smooth?

**Comment by mortenjust** [comment]
A: Was this with setup.sh? Did you clone the linked tensorflow folder too?
B: Or was it with Trainer.app?

**Comment by BFMarks** [comment]
it was ./setup.sh and I git cloned the tensorflow source to the tensorflow folder

**Comment by BFMarks** [comment]
Also, the Trainer project looks really cool.  Going through it now.  My theory is that ML just needs better frameworks so developers can start putting it in their app and not have to learn the low-level code.  I don't know if I'll be able to add to the source code but if I get it working, I'd be happy to add to the wiki about solutions I've found for errors and testing environments.

**Comment by mortenjust** [comment]
Sounds great! The Trainer.app should be able to do everything for you if you follow the steps in its readme.md. So far I've only tested it with a separate user on my Mac. I'm very curious to hear how it works out for you

(and I completely agree about the frameworks)

**Comment by BFMarks** [comment]
Hey Morten,

So I got it working.  Very interesting stuff!  But the phone actually crashes from the processing power.  I can't really see this being scalable from device side :( I think it's going to have to be on AWS Lambda or something because my 6s+ seems like it can't handle it.  Really cool stuff though!  What are your thoughts?  Do you think it can be optimized on the device side?

**Comment by mortenjust** [comment]
Awesome! How did you get it to work? Trainer.app? 
What is the nature of the crash? Does it freeze, abruptly quit the app, or maybe reboot?
Do you get anything interesting in the console window in Xcode? 

I'm optimistic about running this on the device. Future phones will be better equipped. Future versions of Tensorflow will most likely run on Apple's GPU API, Metal. It works impressively fast on iPhone 7, which means it will be even faster on iPhone 8. Device-side also means no cloud cost, no network lag, and that it is free forever.

I haven't seen my 7plus crash, at most it gets a little warm. I'm booting up my 6S to try now.

**Comment by mortenjust** [comment]
Good news, I think. It works on my 6S. But it does crash because there was a bug in my code, unrelated to Tensorflow. I'll take a look later today and push a new version.

**Comment by BFMarks** [comment]
```
Seen Object. Loading url: nil
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-03-21 14:28:08.443326 Tensorswift[22011:6022124] fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb
```)   - Not sure where the nil value is.

**Comment by BFMarks** [comment]
Ya sounds great man.  Also, in regards to having the ML on the device - definitely good points but there's something said for being able to update the model server side.  Also, with really complicated/large sets of training - you will run into issues with the 90% of devices on the market right now.  Anyway still an interesting discussion!   We'll see how it pans out.

**Comment by mortenjust** [comment]
Yep, I have a good idea where to track down the that nil, stay tuned. I hear you on the large datasets, and updateability. But running the model on every video frame is hard with the cloud. The images are not much bigger than ~120x120, but there are dozens per second. Would be really interesting to see a side by side comparison of cloud vs. device though!

**Comment by BFMarks** [comment]
Awesome man.  I'm just planning on running on still images for a project but I could see how running models on video frames could be interesting!

**Comment by mortenjust** [comment]
Pushed the bug fix and closing this bug. Looking forward to hearing about your progress, cloud or not - and thanks for your courage trying this so early on!

**Comment by BFMarks** [comment]
Of course Morten!  Very cool stuff!
